access development environment email logs:
  title: 'Access development environment mail logs'
  description: 'Allows administrators to view logs of emails that the development environment module has prevented from being sent'

administer development environment settings:
  title: 'Administer development environment settings'
  description: 'Allows administrators to administer settings for the Development Environment module'
