development_environment.email_log:
  title: 'Suppressed Email Log'
  route_name: development_environment.suppressed_email_log_list
  parent: system.admin_reports
  description: 'View log of emails suppressed by the Development Environment module'
