development_environment.email_log:
  title: 'Suppressed Email Log'
  route_name: 'development_environment.suppressed_email_log_list'
  parent: 'system.admin_reports'
  description: 'View log of emails suppressed by the Development Environment module'

development_environment.email_log:
  title: 'Suppressed Email Log'
  route_name: 'development_environment.suppressed_email_log_list'
  parent: 'system.admin_reports'
  description: 'View log of emails suppressed by the Development Environment module'

development_environment.settings_page:
  title: 'Development Environment'
  route_name: 'development_environment.settings_page'
  parent: 'system.admin_config_development'
  description: 'Administer settings for the Development Environment module'
