development_environment.suppressed_email_log_list:
  path: '/admin/reports/email_log'
  defaults:
    _controller: '\Drupal\development_environment\Controller\DevelopmentEnvironmentController::logListPage'
    _title: 'Suppressed Email Log'
  requirements:
    _permission: 'access development environment email logs'

development_environment.suppressed_email_log:
  path: '/admin/reports/email_log/{lid}'
  defaults:
    _controller: '\Drupal\development_environment\Controller\DevelopmentEnvironmentController::mailLogPage'
    _title: 'Suppressed Email'
  requirements:
    _permission: 'access development environment email logs'

development_environment.settings_page:
  path: '/admin/config/development/development_environment'
  defaults:
    _controller: '\Drupal\development_environment\Controller\DevelopmentEnvironmentController::settingsPage'
    _title: 'Development Environment'
  requirements:
    _permission: 'administer development environment settings'
